name: test-build

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    lint:
        runs-on: [self-hosted]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: install yarn
              run: npm install --global yarn
