name: test-build

on:
    schedule:
        - cron: "0 0 * * *"
    repository_dispatch:
        types: [response_time]
    workflow_dispatch:

jobs:
    lint:
        runs-on: [self-hosted]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: install yarn
              run: npm install --global yarn
